[GLOBAL]
pants_version = "2.15.1"

backend_packages.add = [
  "pants.backend.python",
]

[source]
root_patterns = ["python", "airflow"]


[python]
interpreter_constraints = ["==3.10.*"]
enable_resolves = true

